# Generated by Django 3.0.5 on 2022-03-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiter',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='lastname',
        ),
        migrations.AddField(
            model_name='candidate',
            name='phonenumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='companyaddress',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='companyname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='phonenumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='firstname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='lastname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
