# Generated by Django 3.0.5 on 2022-03-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20220318_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtype', models.CharField(max_length=200, null=True)),
                ('jobname', models.CharField(max_length=200, null=True)),
                ('vacancies', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
