# Generated by Django 3.0.5 on 2022-03-20 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='vacancies',
            field=models.IntegerField(null=True),
        ),
    ]
